version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: build
          command: pwsh ./build.ps1

  publish:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: pack
          command: pwsh ./pack.ps1
      - run:
          name: publish
          command: dotnet nuget push --api-key="${NUGET_APIKEY}" artifacts/*.nupkg

workflows:
  build:
    jobs:
      - build
