version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: build
          command: pwsh ./build.ps1

  publish:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout
      - run:
          name: pack-and-publish
          command: |
            pwsh ./pack.ps1
            dotnet nuget push --source "https://api.nuget.org/v3/index.json" --api-key="${NUGET_APIKEY}" ~/project/artifacts/*.nupkg
      - store_artifacts:
          path: ~/project/artifacts

workflows:
  build-publish:
    jobs:
      - build
      - publish:
          context: xerris-core
          requires:
            - build
          filters:
            branches:
              only: main
