version: 2.1

jobs:
  build:
    docker:
      - image: microsoft/dotnet:latest
    steps:
      - checkout
      - run:
          name: build
          command: pwsh ./build.ps1

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
