version: 2.1

jobs:
  build:
    docker:
      - image: microsoft/dotnet:latest
        # TODO
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: build
          command: pwsh ./build.ps1

  publish:
    docker:
      - image: microsoft/dotnet:latest
      # TODO
      # auth:
      #   username: mydockerhub-user
      #   password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: pack
          command: pwsh ./pack.ps1
      - run:
          name: publish
          command: dotnet nuget push --api-key="${NUGET_APIKEY}" artifacts/*.nupkg

workflows:
  build:
    jobs:
      - build

  build-and-publish:
    jobs:
      - build
      - publish:
          filters:
            branches:
              only: main
          requires:
            - build
